### ISSUE TITLE
Exception from Broker on Delete Asset

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-extensions#209]
I created an asset and contract definition. Unfortunately, I receive an error on deleting the contract definition. Problem seems to be, that neither Connector nor Assets are register at Broker. Unfortunately, there is no error message about a registration failure. 

On asset delete request, a RejectionMessage instead of a ResultMessage is provided by broker.
`Caused by: org.eclipse.edc.spi.EdcException: Received class de.fraunhofer.iais.eis.RejectionMessageImpl but expected [class de.fraunhofer.iais.eis.ResultMessageImpl].`

A debug session with Broker operator is scheduled for Monday, 20th.

```
broker-extension-edc_demo-1    | 2023-03-16 10:03:42 Registering resource test-urn:artifact:test at broker 
broker-extension-edc_demo-1    | 2023-03-16 10:04:20 JerseyExtension: Unexpected exception caught 
broker-extension-edc_demo-1    | org.eclipse.edc.spi.EdcException: Failed to receive result message
broker-extension-edc_demo-1    |        at de.sovity.extension.broker.service.IdsBrokerServiceImpl.findResourceIdsByQuery(IdsBrokerServiceImpl.java:201)
broker-extension-edc_demo-1    |        at de.sovity.extension.broker.service.IdsBrokerServiceImpl.getDeletedBrokerIds(IdsBrokerServiceImpl.java:315)
broker-extension-edc_demo-1    |        at de.sovity.extension.broker.service.IdsBrokerServiceImpl.resolveDeletedBrokerIds(IdsBrokerServiceImpl.java:242)
broker-extension-edc_demo-1    |        at de.sovity.extension.broker.service.IdsBrokerServiceImpl.on(IdsBrokerServiceImpl.java:233)
broker-extension-edc_demo-1    |        at org.eclipse.edc.connector.core.event.EventRouterImpl.lambda$publish$0(EventRouterImpl.java:54)
broker-extension-edc_demo-1    |        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
broker-extension-edc_demo-1    |        at org.eclipse.edc.connector.core.event.EventRouterImpl.publish(EventRouterImpl.java:54)
broker-extension-edc_demo-1    |        at org.eclipse.edc.connector.service.contractdefinition.ContractDefinitionEventListener.deleted(ContractDefinitionEventListener.java:54)
broker-extension-edc_demo-1    |        at org.eclipse.edc.connector.service.contractdefinition.ContractDefinitionServiceImpl.lambda$delete$4(ContractDefinitionServiceImpl.java:80)
broker-extension-edc_demo-1    |        at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037)
broker-extension-edc_demo-1    |        at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054)
broker-extension-edc_demo-1    |        at org.eclipse.edc.spi.observe.Observable.invokeForEach(Observable.java:47)
broker-extension-edc_demo-1    |        at org.eclipse.edc.connector.service.contractdefinition.ContractDefinitionServiceImpl.lambda$delete$5(ContractDefinitionServiceImpl.java:80)
broker-extension-edc_demo-1    |        at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:63)
broker-extension-edc_demo-1    |        at org.eclipse.edc.connector.service.contractdefinition.ContractDefinitionServiceImpl.delete(ContractDefinitionServiceImpl.java:73)
broker-extension-edc_demo-1    |        at org.eclipse.edc.connector.api.datamanagement.contractdefinition.ContractDefinitionApiController.deleteContractDefinition(ContractDefinitionApiController.java:120)
broker-extension-edc_demo-1    |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
broker-extension-edc_demo-1    |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
broker-extension-edc_demo-1    |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
broker-extension-edc_demo-1    |        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
broker-extension-edc_demo-1    |        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
broker-extension-edc_demo-1    | Caused by: java.lang.RuntimeException: org.eclipse.edc.spi.EdcException: Received class de.fraunhofer.iais.eis.RejectionMessageImpl but expected [class de.fraunhofer.iais.eis.ResultMessageImpl].
broker-extension-edc_demo-1    |        at org.eclipse.edc.protocol.ids.api.multipart.dispatcher.sender.IdsMultipartSender.lambda$send$0(IdsMultipartSender.java:175)
broker-extension-edc_demo-1    |        at org.eclipse.edc.protocol.ids.message.FutureCallback.onResponse(FutureCallback.java:46)
broker-extension-edc_demo-1    |        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
broker-extension-edc_demo-1    |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
broker-extension-edc_demo-1    |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
broker-extension-edc_demo-1    |        ... 1 more
broker-extension-edc_demo-1    | Caused by: org.eclipse.edc.spi.EdcException: Received class de.fraunhofer.iais.eis.RejectionMessageImpl but expected [class de.fraunhofer.iais.eis.ResultMessageImpl].
broker-extension-edc_demo-1    |        at org.eclipse.edc.protocol.ids.api.multipart.dispatcher.sender.IdsMultipartSender.checkResponseType(IdsMultipartSender.java:229)
broker-extension-edc_demo-1    |        at org.eclipse.edc.protocol.ids.api.multipart.dispatcher.sender.IdsMultipartSender.lambda$send$0(IdsMultipartSender.java:170)
broker-extension-edc_demo-1    |        ... 5 more
broker-extension-edc_demo-1    |
```

```json
[
    {
        "createdAt": 1678961013730,
        "properties": {
            "asset:prop:keywords": "test",
            "asset:prop:name": "test",
            "asset:prop:curatorOrganizationName": "sovity GmbH",
            "asset:prop:description": "test",
            "asset:prop:id": "urn:artifact:test",
            "http://w3id.org/mds#dataCategory": "RoadworksRoadConditions",
            "asset:prop:originator": "http://edc_demo:11003/api/v1/ids/data",
            "asset:prop:language": "https://w3id.org/idsa/code/EN"
        },
        "id": "urn:artifact:test"
    }
]
```

```json
[
    {
        "createdAt": 1678961022202,
        "id": "test",
        "accessPolicyId": "always-true",
        "contractPolicyId": "always-true",
        "criteria": [
            {
                "operandLeft": "asset:prop:id",
                "operator": "in",
                "operandRight": [
                    "urn:artifact:test"
                ]
            }
        ]
    }
]
```

**Comment by tmberthold** [comment]
After first debugging, the Broker seems to not get a valid DAT, at least that's the Payload of the RejectionMessage in debug:

![image](https://user-images.githubusercontent.com/75306992/226272206-d4fbed17-bf75-4dd0-8fba-0395b0c856de.png)

**Comment by SebastianOpriel** [comment]
Indeed, this was a problem between Broker and DAPS, which had its origin in a DNS failure. The problem could be solved. Everything should run as intended now.
