### ISSUE TITLE
Fetch Status Issue inside the Catalog Browser 

### ISSUE THREAD

**Issue by dcarmen1** [sovity/edc-extensions#378]
# Bug Report

## Description:

Inside the catalog browser, at the moment to check the status of the connector, a 502 error message failing for the token is reflected, this behavior began yesterday around 15h (GMT+2) before this time worked correctly, without any changes.
Version of the connector: 3.3.0

### Expected Behavior
Fetch Status 200 for Other Connector Endpoint Catalogs.

### Observed Behavior
Status 502
EDC Backend failed fetching other connector catalog.
Backend message: [{"message":"Failed to obtain token: Server response to Request{method=POST, url=https://daps.mobility-dataspace.eu/token, headers=[Accept:application/json, Content-Type:application/x-www-form-urlencoded]} was not 200 but was 500: Internal server error","type":"BadGateway","path":null,"invalidValue":null}] 

Inside the logs shows the next information:

HTTP client exception caught for request Request{method=POST, url=https://daps.mobility-dataspace.eu/token, headers=[Accept:application/json, Content-Type:application/x-www-form-urlencoded]} 
org.eclipse.edc.spi.http.EdcHttpClientException: Server response to Request{method=POST, url=https://daps.mobility-dataspace.eu/token, headers=[Accept:application/json, Content-Type:application/x-www-form-urlencoded]} was not 200 but was 500: Internal server error
	at org.eclipse.edc.spi.http.FallbackFactories.lambda$statusMustBe$3(FallbackFactories.java:62)
	at dev.failsafe.Fallback.lambda$builderOfException$0(Fallback.java:106)
	at dev.failsafe.internal.FallbackImpl.apply(FallbackImpl.java:58)
	at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:62)
	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:193)
	at dev.failsafe.CallImpl.execute(CallImpl.java:33)
	at dev.failsafe.okhttp.FailsafeCall.execute(FailsafeCall.java:121)
	at org.eclipse.edc.connector.core.base.EdcHttpClientImpl.execute(EdcHttpClientImpl.java:66)
	at org.eclipse.edc.iam.oauth2.client.Oauth2ClientImpl.requestToken(Oauth2ClientImpl.java:52)
	at org.eclipse.edc.spi.result.Result.compose(Result.java:147)
	at org.eclipse.edc.iam.oauth2.identity.Oauth2ServiceImpl.obtainClientCredentials(Oauth2ServiceImpl.java:75)
	at org.eclipse.edc.protocol.ids.service.DynamicAttributeTokenServiceImpl.obtainDynamicAttributeToken(DynamicAttributeTokenServiceImpl.java:46)
	at org.eclipse.edc.protocol.ids.api.multipart.dispatcher.sender.IdsMultipartSender.send(IdsMultipartSender.java:78)
	at org.eclipse.edc.protocol.ids.api.multipart.dispatcher.IdsMultipartRemoteMessageDispatcher.send(IdsMultipartRemoteMessageDispatcher.java:68)
	at org.eclipse.edc.connector.core.base.RemoteMessageDispatcherRegistryImpl.send(RemoteMessageDispatcherRegistryImpl.java:49)
	at de.sovity.extension.broker.service.IdsBrokerServiceImpl.registerConnectorAtBroker(IdsBrokerServiceImpl.java:106)
	at de.sovity.extension.broker.BrokerExtension.start(BrokerExtension.java:268)
	at org.eclipse.edc.boot.system.injection.lifecycle.StartPhase.start(StartPhase.java:34)
	at org.eclipse.edc.boot.system.injection.lifecycle.ExtensionLifecycleManager.start(ExtensionLifecycleManager.java:78)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.eclipse.edc.boot.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:72)
	at org.eclipse.edc.boot.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:141)
	at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:202)
	at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:84)
	at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:72)

 Failed to obtain token: Server response to Request{method=POST, url=https://daps.mobility-dataspace.eu/token, headers=[Accept:application/json, Content-Type:application/x-www-form-urlencoded]} was not 200 but was 500: Internal server error

**Comment by tmberthold** [comment]
I think there is a problem on the MDS-DAPS side then, because the EDC gets a 500 error message back from the DAPS instead of a normal response.

Failed to obtain token: Server response to Request -> was not 200 but was 500 -> **BadGateway**

..will remove the bug label.
@ip312

**Comment by ip312** [comment]
Yes, that was the problem with DAPS, the issue can be closed.
