### ISSUE TITLE
Absolute path Keystore location cannot be handled

### ISSUE THREAD

**Issue by Martin0815bla** [sovity/edc-extensions#92]
# Bug Report

## Description

According to README.md the location of the keystore (.jks file) needs to be specified in docker-compose.yaml.
The default settings in parameter EDC_KEYSTORE suggests an absolute path while the README.md suggests a relative path 
resources/vault/edc/
Providing an absolute path anywhere in the file system yields a fileNotFound Exception for docker compose up

### Expected Behavior

Accept an absolute path configuration of the keystore file anywhere on the file system

### Observed Behavior

edc-ui  | 2023/02/07 11:46:47 [notice] 1#1: start worker processes
edc-ui  | 2023/02/07 11:46:47 [notice] 1#1: start worker process 58
edc-ui  | 2023/02/07 11:46:47 [notice] 1#1: start worker process 60
edc-ui  | 2023/02/07 11:46:47 [notice] 1#1: start worker process 62
edc-ui  | 2023/02/07 11:46:47 [notice] 1#1: start worker process 64
edc-ui  | 2023/02/07 11:46:47 [notice] 1#1: start worker process 65
edc-ui  | 2023/02/07 11:46:47 [emerg] 58#58: io_setup() failed (38: Function not implemented)
edc-ui  | 2023/02/07 11:46:47 [emerg] 60#60: io_setup() failed (38: Function not implemented)
edc-ui  | 2023/02/07 11:46:47 [emerg] 62#62: io_setup() failed (38: Function not implemented)
edc-ui  | 2023/02/07 11:46:47 [emerg] 64#64: io_setup() failed (38: Function not implemented)
edc-ui  | 2023/02/07 11:46:47 [emerg] 65#65: io_setup() failed (38: Function not implemented)
edc     | 2023-02-07 11:46:49 Configuration file does not exist: dataspaceconnector-configuration.properties. Ignoring. 
edc     | 2023-02-07 11:46:49 Initialized FS Configuration 
edc     | 2023-02-07 11:46:50 **Error booting runtime: Key store does not exist: /Users/A307961/Daten/Projekte/MDP/MDS-Anbindung/connector/tmp/cert.jks** 
edc     | org.eclipse.edc.spi.EdcException: Key store does not exist: /Users/A307961/Daten/Projekte/MDP/MDS-Anbindung/connector/tmp/cert.jks
edc     | 	at org.eclipse.edc.vault.filesystem.FsVaultExtension.loadKeyStore(FsVaultExtension.java:83)
edc     | 	at org.eclipse.edc.vault.filesystem.FsVaultExtension.initialize(FsVaultExtension.java:60)
edc     | 	at org.eclipse.edc.boot.system.injection.lifecycle.InitializePhase.initialize(InitializePhase.java:37)
edc     | 	at org.eclipse.edc.boot.system.injection.lifecycle.ExtensionLifecycleManager.initialize(ExtensionLifecycleManager.java:61)
edc     | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
edc     | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
edc     | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
edc     | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
edc     | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
edc     | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
edc     | 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
edc     | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
edc     | 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
edc     | 	at org.eclipse.edc.boot.system.ExtensionLoader.bootServiceExtensions(ExtensionLoader.java:67)
edc     | 	at org.eclipse.edc.boot.system.runtime.BaseRuntime.bootExtensions(BaseRuntime.java:152)
edc     | 	at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:222)
edc     | 	at org.eclipse.edc.boot.system.runtime.BaseRuntime.boot(BaseRuntime.java:87)
edc     | 	at org.eclipse.edc.boot.system.runtime.BaseRuntime.main(BaseRuntime.java:75)
edc     | 
edc exited with code 255

## Steps to Reproduce

Specify an existing keystore file in docker-compose.yaml

## Context Information

specifying the keystore.jks in /resources/vault/edc/ (absolute path although it is a relative path to the installation) resolves the problem

-   Time: until 07.02.2022
-   Logs: see above
-   Parameter: see above
-   OS: MacOS Ventura 13.0.1

**Comment by omarsilva1** [comment]
Hello, it doesnt seem to be possible to pass an absolute path of the host machine as an argument in docker-compose due to security reasons. You can see a similar issue in the docker compose repository: https://github.com/docker/compose/issues/4849 

The linked documentation https://docs.docker.com/engine/reference/builder/#copy references `The <src> path must be inside the context of the build; you cannot COPY ../something /something, because the first step of a docker build is to send the context directory (and subdirectories) to the docker daemon.`

Can you point where in the documentation an absolute path is suggested? This might be misleading
